# Generated by Django 5.2 on 2025-05-11 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_experience'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icon_class', models.CharField(blank=True, help_text='Örn: fa fa-html5', max_length=100)),
                ('level', models.IntegerField(default=0, help_text='0-100 arası beceri seviyesi')),
            ],
        ),
    ]
